sudo: required
language: python
python:
  - 3.6

before_install:
  - sudo apt-get install -y libboost-python-dev

install:
  - git clone --recursive https://github.com/AppImage/AppImageUpdate
  - pushd AppImageUpdate
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_QT_UI=OFF
  - make -j$(nproc)
  - sudo make install
  - popd

script:
  - python setup.py develop
  - py.test
