sudo: required
language: generic

install:
  # build AppImageUpdate outside the build directory
  - pushd /tmp
  - git clone --recursive https://github.com/AppImage/AppImageUpdate
  - pushd AppImageUpdate
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_QT_UI=OFF
  - make -j$(nproc)
  - sudo make install
  - popd
  - popd

before_script:
  # installing boost::python from source is annoying
  # therefore using a miniconda environment for testing
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
  - bash Miniconda3-latest-Linux-x86_64.sh -b -p conda-env/usr -f
  - . conda-env/usr/bin/activate
  - conda install -c meznom boost-python

script:
  - python setup.py develop
  - py.test tests/
